language: python
python:
  - "3.7"

install:
  - pip install .[dev]

script:
  - python -m unittest discover tests -p "*.py"
  - flake8 . --select=C,E,F,W,B,B9 --ignore=B305,E501,E722,F401
  - cd docs
  - make html
